Repository pierooo/SystemRestauracji_v1, pull requests merged in 2023-01, with the labels that each got.

#8 Added GetProducts
  Firma/ViewModels/GetProductsViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/GetProductsView.xaml
  Firma/Views/GetProductsView.xaml.cs
  Firma/Views/MainWindow.xaml
  Firma/Views/MainWindowResources.xaml
Labels: feature

#9 Fixed products displaying
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/MainWindow.xaml
Labels: bug

#14 Added Categories displaying
  Firma/ViewModels/GetCategoriesViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/GetCategoriesView.xaml
  Firma/Views/GetCategoriesView.xaml.cs
  Firma/Views/MainWindow.xaml
  Firma/Views/MainWindowResources.xaml
Labels: feature

#16 Added enum for order status
  Firma/Models/BusinessLogic/OrderStatus.cs
Labels: feature

#18 Added restaurant tables displaying
  Firma/ViewModels/GetRestaurantTablesViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/GetRestaurantTablesView.xaml
  Firma/Views/GetRestaurantTablesView.xaml.cs
  Firma/Views/MainWindow.xaml
  Firma/Views/MainWindowResources.xaml
Labels: feature

#21 Added reservations displaying
  Firma/Models/EntitiesForView/ReservationForAllView.cs
  Firma/ViewModels/GetReservationsViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/GetReservationsView.xaml
  Firma/Views/GetReservationsView.xaml.cs
  Firma/Views/MainWindow.xaml
  Firma/Views/MainWindowResources.xaml
Labels: feature

#24 Added workstationsdevicelinks displaying
  Firma/Models/EntitiesForView/WorkstationDeviceLinksForAllView.cs
  Firma/ViewModels/GetWorkstationDeviceLinksViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/GetWorkstationDeviceLinksView.xaml
  Firma/Views/GetWorkstationDeviceLinksView.xaml.cs
  Firma/Views/MainWindow.xaml
  Firma/Views/MainWindowResources.xaml
Labels: feature

#23 Added Workstations
  Firma/Models/EntitiesForView/WorkstationForAllView.cs
  Firma/ViewModels/GetWorkstationsViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/GetWorkstationsView.xaml
  Firma/Views/GetWorkstationsView.xaml.cs
  Firma/Views/MainWindow.xaml
  Firma/Views/MainWindowResources.xaml
Labels: feature

#26 clean up develop
  Firma/Helpers/BaseCommand.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/ViewModels/WszystkieWorkstationViewModel.cs
  Firma/Views/MainWindowResources.xaml
Labels: bug

#27 Added Documents displaying
  Firma/Models/EntitiesForView/DocumentForAllView.cs
  Firma/ViewModels/GetDocumentsViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/GetDocumentsView.xaml
  Firma/Views/GetDocumentsView.xaml.cs
  Firma/Views/MainWindow.xaml
  Firma/Views/MainWindowResources.xaml
Labels: feature

#28 Changes in top menu
  Firma/Views/MainWindow.xaml
Labels: bug

#32 Logic/fixed statuses and added own connection string
  Firma/Models/BusinessLogic/Status.cs
  Firma/connections.config
Labels: bug

#33 Fixed toogleMenu
  Firma/Views/MainWindow.xaml
Labels: bug

#34 Get all/get devices
  Firma/ViewModels/GetDevicesViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/GetDevicesView.xaml
  Firma/Views/GetDevicesView.xaml.cs
  Firma/Views/MainWindow.xaml
  Firma/Views/MainWindowResources.xaml
Labels: feature, Ready to merge

#35 Added fees to System
  Firma/Models/BusinessLogic/Status.cs
  Firma/Views/MainWindow.xaml
Labels: feature

#36 Added orders displaying
  Firma/Models/BusinessLogic/StatusMapper.cs
  Firma/Models/EntitiesForView/OrderForAllView.cs
  Firma/ViewModels/GetOpenedOrdersViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/GetOrdersView.xaml
  Firma/Views/GetOrdersView.xaml.cs
  Firma/Views/MainWindow.xaml
  Firma/Views/MainWindowResources.xaml
Labels: feature

#37 Added OrderDetails View after click to order
  Firma/Models/EntitiesForView/OrderDetailsForAllView.cs
  Firma/Models/EntitiesForView/OrderForOrderDetailsView.cs
  Firma/SystemRestauracji.csproj
  Firma/ViewModels/GetOrderDetailsViewModel.cs
  Firma/ViewModels/GetOrdersViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/GetOrderDetailsView.xaml
  Firma/Views/GetOrderDetailsView.xaml.cs
  Firma/Views/GetOrdersView.xaml
  Firma/Views/MainWindowResources.xaml
Labels: feature

#40 Fixed Orders details displaying
  Firma/ViewModels/GetOrderDetailsViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/GetOrderDetailsView.xaml
Labels: bug

#41 Added logic if click on one of categories you should see products inc…
  Firma/Models/BusinessLogic/Status.cs
  Firma/Models/Correspondences/AddProductToOrder.cs
  Firma/Models/EntitiesForView/OrderForOrderDetailsView.cs
  Firma/ViewModels/GetCategoriesViewModel.cs
  Firma/ViewModels/GetOrderDetailsViewModel.cs
  Firma/ViewModels/GetOrdersViewModel.cs
  Firma/ViewModels/GetProductsViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/GetCategoriesView.xaml
  Firma/Views/GetOrderDetailsView.xaml
  Firma/Views/GetProductsView.xaml
Labels: feature

#42 Get all/get payments : Fee, Open, Done.
  Firma/Models/EntitiesForView/PaymentsForAllView.cs
  Firma/ViewModels/GetPaymentsViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/GetPaymentsView.xaml
  Firma/Views/GetPaymentsView.xaml.cs
  Firma/Views/MainWindow.xaml
  Firma/Views/MainWindowResources.xaml
Labels: feature

#44 Renamed Base Class
  Firma/Themes/Generic.xaml
  Firma/Views/AddViewBase.cs
  Firma/Views/GetAllViewBase.cs
  Firma/Views/GetCategoriesView.xaml
  Firma/Views/GetCategoriesView.xaml.cs
  Firma/Views/GetCompaniesView.xaml
  Firma/Views/GetCompaniesView.xaml.cs
  Firma/Views/GetDevicesView.xaml
  Firma/Views/GetDevicesView.xaml.cs
  Firma/Views/GetDocumentsView.xaml
  Firma/Views/GetDocumentsView.xaml.cs
  Firma/Views/GetInvoicesView.xaml
  Firma/Views/GetInvoicesView.xaml.cs
  Firma/Views/GetOrderDetailsView.xaml
  Firma/Views/GetOrderDetailsView.xaml.cs
  Firma/Views/GetOrdersView.xaml
  Firma/Views/GetOrdersView.xaml.cs
  Firma/Views/GetPaymentsView.xaml
  Firma/Views/GetPaymentsView.xaml.cs
  Firma/Views/GetProductsView.xaml
  Firma/Views/GetProductsView.xaml.cs
  Firma/Views/GetReservationsView.xaml
  Firma/Views/GetReservationsView.xaml.cs
  Firma/Views/GetRestaurantTablesView.xaml
  Firma/Views/GetRestaurantTablesView.xaml.cs
  Firma/Views/GetUsersView.xaml
  Firma/Views/GetUsersView.xaml.cs
  Firma/Views/GetWorkstationDeviceLinksView.xaml
  Firma/Views/GetWorkstationDeviceLinksView.xaml.cs
  Firma/Views/GetWorkstationsView.xaml
  Firma/Views/GetWorkstationsView.xaml.cs
  Firma/Views/NowaKategoriaView.xaml
  Firma/Views/NowaKategoriaView.xaml.cs
  Firma/Views/NowyDostawcaView.xaml
  Firma/Views/NowyDostawcaView.xaml.cs
  Firma/Views/NowyPracownikView.xaml
  Firma/Views/NowyPracownikView.xaml.cs
  Firma/Views/NowyTypkategoriiView.xaml
  Firma/Views/NowyTypkategoriiView.xaml.cs
  Firma/Views/WszyscyDostawcyView.xaml
  Firma/Views/WszyscyDostawcyView.xaml.cs
  Firma/Views/WszyscyPracownicyView.xaml
  Firma/Views/WszyscyPracownicyView.xaml.cs
  Firma/Views/WszystkieKategorieView.xaml
  Firma/Views/WszystkieKategorieView.xaml.cs
  Firma/Views/WszystkieTowaryView.xaml
  Firma/Views/WszystkieTowaryView.xaml.cs
  Firma/Views/WszystkieTypyKategoriiView.xaml
  Firma/Views/WszystkieTypyKategoriiView.xaml.cs
  Firma/Views/WszystkieWorkstationView.xaml
  Firma/Views/WszystkieWorkstationView.xaml.cs
  Firma/connections.config
Labels: bug

#45 Added Category adding
  Firma/App.Config
  Firma/Models/Entities/RestaurantSystemEntities.Designer.cs
  Firma/Models/Entities/RestaurantSystemEntities.edmx
  Firma/Models/Entities/RestaurantSystemEntities.edmx.diagram
  Firma/SystemRestauracji.csproj
  Firma/ViewModels/Abstract/ItemViewModel.cs
  Firma/ViewModels/AddCategoryViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/AddCategoryView.xaml
  Firma/Views/AddCategoryView.xaml.cs
  Firma/Views/AddViewBase.cs
  Firma/Views/MainWindow.xaml
  Firma/Views/MainWindowResources.xaml
  Firma/connections.config
Labels: feature

#47 Added employee adding
  Firma/Models/BusinessLogic/Role.cs
  Firma/ViewModels/AddEmployeeViewModel.cs
  Firma/ViewModels/AddProductViewModel.cs
  Firma/ViewModels/GetUsersViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/AddEmployeeView.xaml
  Firma/Views/AddEmployeeView.xaml.cs
  Firma/Views/GetUsersView.xaml
  Firma/Views/MainWindow.xaml
  Firma/Views/MainWindowResources.xaml
Labels: feature

#52 SmallCleanup
  Firma/ViewModels/AddWorkstationDeviceLinkViewModel.cs
  Firma/Views/AddWorkstationDeviceLinkView.xaml
  Firma/Views/StyleZakladekResources.xaml
Labels: bug

#53 Logic/add order details position logic
  Firma/App.Config
  Firma/Models/BusinessLogic/Calculations/Calculate.cs
  Firma/Models/Correspondences/AddProductToOrder.cs
  Firma/Models/Entities/RestaurantSystemEntities.Designer.cs
  Firma/Models/Entities/RestaurantSystemEntities.edmx
  Firma/ViewModels/AddOrderDetailsProductDetailsViewModel.cs
  Firma/ViewModels/AddOrderViewModel.cs
  Firma/ViewModels/GetOrderDetailsViewModel.cs
  Firma/ViewModels/GetProductsViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/AddOrderDetailsProductDetailsView.xaml
  Firma/Views/AddOrderDetailsProductDetailsView.xaml.cs
  Firma/Views/AddOrderView.xaml
  Firma/Views/AddOrderView.xaml.cs
  Firma/Views/MainWindow.xaml
  Firma/Views/MainWindowResources.xaml
Labels: feature

#56 Added ClientAdd view and provided buttons add refresh in Get Views
  Firma/SystemRestauracji.csproj
  Firma/Themes/Generic.xaml
  Firma/ViewModels/Abstract/ViewModelBase.cs
  Firma/ViewModels/AddClientViewModel.cs
  Firma/ViewModels/GetOrdersViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/AddClientView.xaml
  Firma/Views/AddClientView.xaml.cs
  Firma/Views/Content/Icons/add-button.png
  Firma/Views/Content/Icons/refresh.png
  Firma/Views/MainWindow.xaml
  Firma/Views/MainWindow.xaml.cs
  Firma/Views/MainWindowResources.xaml
Labels: feature

#57 Added button to CLose all tabs
  Firma/SystemRestauracji.csproj
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/Content/Icons/cancel.png
  Firma/Views/MainWindow.xaml
Labels: feature

#59 Added Company adding
  Firma/ViewModels/AddCompanyViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/AddCompanyView.xaml
  Firma/Views/AddCompanyView.xaml.cs
  Firma/Views/MainWindow.xaml
  Firma/Views/MainWindowResources.xaml
Labels: feature

#60 Added Reservation add view
  Firma/ViewModels/AddCompanyViewModel.cs
  Firma/ViewModels/AddReservationViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/AddReservationView.xaml
  Firma/Views/AddReservationView.xaml.cs
  Firma/Views/MainWindow.xaml
  Firma/Views/MainWindowResources.xaml
Labels: feature

#61 Finished First part working for close order, need adjustment close or…
  Firma/Models/Correspondences/CloseOrder.cs
  Firma/ViewModels/CloseOrderViewModel.cs
  Firma/ViewModels/GetOrdersViewModel.cs
  Firma/ViewModels/MainWindowViewModel.cs
  Firma/Views/MainWindow.xaml
Labels: feature
